#!/bin/ksh
# $MirBSD: install-sh,v 1.2 2004/11/10 20:54:33 tg Exp $
# _MirBSD: contrib/gnu/aux/install-sh,v 1.1 2004/08/04 11:26:12 tg Stab $
#-
# Copyright (c) 2004
#	Thorsten "mirabile" Glaser <tg@66h.42h.de>
#
# Licensee is hereby permitted to deal in this work without restric-
# tion, including unlimited rights to use, publically perform, modi-
# fy, merge, distribute, sell, give away or sublicence, provided the
# above copyright notices, these terms and the disclaimer are retai-
# ned in all redistributions, or reproduced in accompanying documen-
# tation or other materials provided with binary redistributions.
#
# Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
# any kind, expressed or implied, to the maximum extent permitted by
# applicable law, but with the warranty of being written without ma-
# licious intent or gross negligence; in no event shall licensor, an
# author or contributor be held liable for any damage, direct, indi-
# rect or other, however caused, arising in any way out of the usage
# of covered work, even if advised of the possibility of such damage.


set +o sh +o posix

allargs="$*"

if [[ $allargs != *@(-t=|-b=)* ]]; then
	exec /usr/bin/install "$@"
fi

args=
d=0

while getopts "B:b:Ccdf:g:m:o:pSst:" opt; do
	case $opt in
	B)	args="$args -B $OPTARG"	;;
	b)	trans_b="${OPTARG#=}"	;;
	C)	args="$args -C"		;;
	c)	args="$args -c"		;;
	d)	d=1; args="$args -d"	;;
	f)	args="$args -f $OPTARG"	;;
	g)	args="$args -g $OPTARG"	;;
	m)	args="$args -m $OPTARG"	;;
	o)	args="$args -o $OPTARG"	;;
	p)	args="$args -p"		;;
	S)	args="$args -S"		;;
	s)	args="$args -s"		;;
	t)	trans_t="${OPTARG#=}"	;;
	esac
done
shift $((OPTIND - 1))

[[ $d = 1 ]] && exec /usr/bin/install $args "$@"

set -A sources -- "$@"
let numsrcs=${#sources[@]}

if (( numsrcs < 2 )); then
	print "Syntax: $0 [-bCcdpSs] [-B suf] [-f flag]"
	print "\t[-g grp] [-m mode] [-o owner] [-b=x -t=x] srcs ... dst"
	exit 1
fi

let dstoff="numsrcs - 1"
let i=0

target="${sources[dstoff]}"

while (( i < dstoff )); do
	src="${sources[i]}"
	if [[ -d $target ]]; then
		dst="$target/${src##*/}"
	else
		dst="$target"
	fi

	dstdir="${dst%/*}"
	dstfile="${dst##*/}"

	if [[ -n $trans_t ]]; then
		dsttmp="$(basename "$dst" $trans_b \
		    | sed $trans_t)$trans_b"
		[[ -n $dsttmp ]] && dstfile="$dsttmp"
	fi

	/usr/bin/install $args "$src" "${dstdir}/${dstfile}" || exit 1

	let i+=1
done
exit 0
