#!/bin/sh
# $MirOS: contrib/code/jupp/install-sh,v 1.7 2006/10/16 18:49:43 tg Exp $
# _MirOS: contrib/gnu/aux/install-sh,v 1.12 2006/10/16 18:46:41 tg Exp $
#-
# Copyright (c) 2004, 2005, 2006
#	Thorsten Glaser <tg@mirbsd.de>
#
# Licensee is hereby permitted to deal in this work without restric-
# tion, including unlimited rights to use, publicly perform, modify,
# merge, distribute, sell, give away or sublicence, provided all co-
# pyright notices above, these terms and the disclaimer are retained
# in all redistributions or reproduced in accompanying documentation
# or other materials provided with binary redistributions.
#
# Advertising materials mentioning features or use of this work must
# display the following acknowledgement:
#	This product includes material provided by Thorsten Glaser.
#
# Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
# express, or implied, to the maximum extent permitted by applicable
# law, without malicious intent or gross negligence; in no event may
# licensor, an author or contributor be held liable for any indirect
# or other damage, or direct damage except proven a consequence of a
# direct error of said person and intended use of this work, loss or
# other issues arising in any way out of its use, even if advised of
# the possibility of such damage or existence of a defect.

if test x"$KSH_VERSION" = x; then
	if test x"$MKSH" = x; then
		MKSH=/bin/mksh
	fi
	if test -f $MKSH; then
		SHELL=$MKSH
	elif test x"`mksh -c 'echo foo'`" = xfoo; then
		MKSH=mksh
		SHELL=mksh
	else
		MKSH=
	fi
	if test -n "$MKSH"; then
		export SHELL
		case $# in
		0)	exec $MKSH "$0" ;;
		*)	exec $MKSH "$0" "$@" ;;
		esac
	fi
	# Only here if spawning mksh failed
	test x"$BASH_VERSION" = x && for i in {,/usr{,/local},/sw}/bin; do
		if test -f $i/bash; then
			SHELL=$i/bash
			export SHELL
			case $# in
			0)	exec $i/bash "$0" ;;
			*)	exec $i/bash "$0" "$@" ;;
			esac
		fi
	done
fi

# XXX how to check for ksh88?
if [ -n "$BASH_VERSION" ]; then
	shopt -s extglob
	p=echo
elif [ -n "$SH_VERSION" ]; then
	case $SH_VERSION in
	*KSH*)
		set +o sh +o posix
		p=print
		;;
	esac
elif [[ -n $KSH_VERSION ]]; then
	p=print
fi

if [ -z "$p" ]; then
	echo "Shell not supported; go to http://mirbsd.de/mksh"
	exit 1
fi

allargs="$*"

installprog=/usr/bin/install
test -x /usr/ucb/install && installprog=/usr/ucb/install

if [[ $allargs != *@(-t=|-b=)* && -z $SFUDIR ]]; then
	exec $installprog "$@"
fi

args=
parg=
marg=
d=0
m=

while getopts "B:b:Ccdf:g:m:o:pSst:" opt; do
	case $opt in
	B)	args="$args -B $OPTARG"	;;
	b)	trans_b="${OPTARG#=}"	;;
	C)	args="$args -C"		;;
	c)	args="$args -c"		;;
	d)	d=1; args="$args -d"	;;
	f)	args="$args -f $OPTARG"	;;
	g)	parg="$parg -g $OPTARG"	;;
	m)	marg="$marg -m $OPTARG"	;;
	o)	parg="$parg -o $OPTARG"	;;
	p)	args="$args -p"		;;
	S)	args="$args -S"		;;
	s)	args="$args -s"		;;
	t)	trans_t="${OPTARG#=}"	;;
	esac
done
shift $((OPTIND - 1))

# we ignore requests for setting UID/GID on Interix
if [[ -n $SFUDIR ]]; then
	# on Interix, install(1) cannot make directories
	[[ $d = 1 ]] && exec /bin/mkdir -p $marg "$@"
else
	args="$args $parg"
fi
args="$args $marg"

set -A sources -- "$@"
let numsrcs=${#sources[@]}

if (( numsrcs < 2 )); then
	$p "Syntax: $0 [-bCcdpSs] [-B suf] [-f flag]"
	$p "\t[-g grp] [-m mode] [-o owner] [-b=x -t=x] srcs ... dst"
	exit 1
fi

let dstoff="numsrcs - 1"
let i=0

target="${sources[dstoff]}"

while (( i < dstoff )); do
	src="${sources[i]}"
	if [[ -d $target ]]; then
		dst="$target/${src##*/}"
	else
		dst="$target"
	fi

	dstdir="${dst%/*}"
	dstfile="${dst##*/}"

	if [[ -n $trans_t ]]; then
		dsttmp="$(basename "$dst" $trans_b \
		    | sed $trans_t)$trans_b"
		[[ -n $dsttmp ]] && dstfile="$dsttmp"
	fi

	$installprog $args "$src" "${dstdir}/${dstfile}" || exit 1

	let i++
done
exit 0
