#!/bin/mksh
# $MirOS: contrib/code/jupp/mkinstalldirs,v 1.3 2005/08/26 23:05:11 tg Exp $
# _MirOS: contrib/gnu/aux/mkinstalldirs,v 1.3 2005/08/26 22:55:56 tg Exp $
#-
# Copyright (c) 2004, 2005
#	Thorsten "mirabile" Glaser <tg@66h.42h.de>
#
# Licensee is hereby permitted to deal in this work without restric-
# tion, including unlimited rights to use, publicly perform, modify,
# merge, distribute, sell, give away or sublicence, provided all co-
# pyright notices above, these terms and the disclaimer are retained
# in all redistributions or reproduced in accompanying documentation
# or other materials provided with binary redistributions.
#
# All advertising materials mentioning features or use of this soft-
# ware must display the following acknowledgement:
#	This product includes material provided by Thorsten Glaser.
#
# Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
# any kind, expressed or implied, to the maximum extent permitted by
# applicable law, but with the warranty of being written without ma-
# licious intent or gross negligence; in no event shall licensor, an
# author or contributor be held liable for any damage, direct, indi-
# rect or other, however caused, arising in any way out of the usage
# of this work, even if advised of the possibility of such damage.


# XXX how to check for ksh88?
if [ -n "$BASH_VERSION" ]; then
	shopt -s extglob
	p=echo
elif [ -n "$SH_VERSION" ]; then
	case $SH_VERSION in
	*KSH*)
		set +o sh +o posix
		p=print
		;;
	esac
elif [[ -n $KSH_VERSION ]]; then
	p=print
fi

if [ -z "$p" ]; then
	echo "Shell not supported; go to http://mirbsd.mirsolutions.de/?mksh"
	exit 1
fi

usage()
{
	echo "$0 [-h] [-m mode] dir ..."
	exit 1
}

if [ -n "$BASH_VERSION" ]; then
	typeset -i mode=8#17777
else
	typeset -i8 mode=8#17777
fi

allargs="$*"

[[ $allargs = *@(--help)* || $allargs = *@(--version)* ]] && \
	usage

while getopts "hm:" opt; do
	case $opt in
	h)	usage ;;
	m)	[[ -z $OPTARG ]] && usage
		let mode="8#$OPTARG"
		;;
	esac
done
shift $((OPTIND - 1))

if (( mode > 8#7777 )); then
	exec /bin/mkdir -p -- "$@"
else
	if [ -n "$BASH_VERSION" ]; then
		exec /bin/mkdir -p -m $(printf %o $mode) "$@"
	else
		exec /bin/mkdir -p -m ${mode#8#} "$@"
	fi
fi
