#!/bin/ksh
# $MirBSD: mkinstalldirs,v 1.2 2004/11/10 20:54:33 tg Exp $
# _MirBSD: contrib/gnu/aux/mkinstalldirs,v 1.1 2004/08/04 11:26:12 tg Stab $
#-
# Copyright (c) 2004
#	Thorsten "mirabile" Glaser <tg@66h.42h.de>
#
# Licensee is hereby permitted to deal in this work without restric-
# tion, including unlimited rights to use, publically perform, modi-
# fy, merge, distribute, sell, give away or sublicence, provided the
# above copyright notices, these terms and the disclaimer are retai-
# ned in all redistributions, or reproduced in accompanying documen-
# tation or other materials provided with binary redistributions.
#
# Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
# any kind, expressed or implied, to the maximum extent permitted by
# applicable law, but with the warranty of being written without ma-
# licious intent or gross negligence; in no event shall licensor, an
# author or contributor be held liable for any damage, direct, indi-
# rect or other, however caused, arising in any way out of the usage
# of covered work, even if advised of the possibility of such damage.


set +o sh +o posix

usage()
{
	print "$0 [-h] [-m mode] dir ..."
	exit 1
}

typeset -i8 mode=8#17777

allargs="$*"

[[ $allargs = *@(--help)* || $allargs = *@(--version)* ]] && \
	usage

while getopts "hm:" opt; do
	case $opt in
	h)	usage ;;
	m)	[[ -z $OPTARG ]] && usage
		let mode="8#$OPTARG"
		;;
	esac
done
shift $((OPTIND - 1))

if (( mode > 8#7777 )); then
	exec /bin/mkdir -p -- "$@"
else
	exec /bin/mkdir -p -m ${mode#8#} "$@"
fi
